// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1aoeTPOCyTfJmzCCb6_MFSts8wa_KHo0',
    appId: '1:140562258254:web:2fc4bd70caee8d22d7261f',
    messagingSenderId: '140562258254',
    projectId: 'looklock-bda41',
    authDomain: 'looklock-bda41.firebaseapp.com',
    storageBucket: 'looklock-bda41.appspot.com',
    measurementId: 'G-39VKQXKE33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6O95YTINoEU1KxHHLMonmNO9Wk84Tddw',
    appId: '1:140562258254:android:42c7e6279d82ed93d7261f',
    messagingSenderId: '140562258254',
    projectId: 'looklock-bda41',
    storageBucket: 'looklock-bda41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHJznR5gG5L2p0ga26BR1auOA4tUV52rA',
    appId: '1:140562258254:ios:9c9d7c2e00c61d88d7261f',
    messagingSenderId: '140562258254',
    projectId: 'looklock-bda41',
    storageBucket: 'looklock-bda41.appspot.com',
    iosBundleId: 'com.example.looklockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHJznR5gG5L2p0ga26BR1auOA4tUV52rA',
    appId: '1:140562258254:ios:3e0329b8e07e4fd4d7261f',
    messagingSenderId: '140562258254',
    projectId: 'looklock-bda41',
    storageBucket: 'looklock-bda41.appspot.com',
    iosBundleId: 'com.example.locklockApp.RunnerTests',
  );
}
